"""empty message

Revision ID: 3f8697e7ed25
Revises: None
Create Date: 2015-11-07 12:43:26.364526

"""

# revision identifiers, used by Alembic.
revision = '3f8697e7ed25'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('q', sa.Text(), nullable=False),
    sa.Column('a', sa.Text(), nullable=False),
    sa.Column('cat', sa.String(length=255), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    ### end Alembic commands ###
